image: openjdk:8-jdk
variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.3"
  ANDROID_SDK_TOOLS: "24.4.1"
  #GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
  - git submodule update --init --recursive
  - export ANDROID_HOME=/home/public/android-sdk-linux
  - export PATH=$PATH:/home/public/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  
stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    paths:
    - app/build/outputs/
    
unitTests:
  stage: test
  script:
    - ./gradlew test

functionalTests:
  stage: test
  script:
    - echo no | /home/public/android-sdk-linux/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
    - /home/public/android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
    - ./home/public/android-sdk-linux/wait-for-emulator.sh
    - adb shell input keyevent 82
    - ./gradlew cAT
  artifacts:
    paths:
    - app/build/reports/androidTests/